name: Unit Tests
on:
  push:
    branches: master

jobs:
  check-coding-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check coding style
        uses: jidicula/clang-format-action@master
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: sudo apt install uuid-dev
      - uses: actions/checkout@v2
      - name: make fclean
        run: make fclean
      - name: build project
        run: make
  unit-test:
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: install criterion & gcovr
        run: |
          sudo add-apt-repository ppa:snaipewastaken/ppa
          sudo apt install criterion-dev gcovr
      - name: install dependencies
        run: sudo apt install uuid-dev
      - uses: actions/checkout@v2
      - name: compile tests
        run: make tests_run
