name: "Max size"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - run: sudo npm install -g sloc
    - run: test $(sloc --exclude-dir=assets/,images/ . | grep -i "source" | cut -d ":" -f 2 | xargs) -le 20000
