name: "Max size"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - run: sudo npm install -g sloc
    - run: test $(sloc -exclude assets/ . | grep -i "source" | cut -d ":" -f 2 | xargs | cut -d " " -f1) -le 3000
